### ISSUE TITLE
Too low performance of documentation pages

### ISSUE THREAD

**Issue by ligurio** [tarantool/doc#1205]
I have observed that documentation pages load too slow on a smartphone.
Env: Google Pixel, Android 10, Firefox

Lighthouse shows low performance too - 32%
https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.tarantool.io%2Fru%2Fdoc%2F2.2%2Fbook%2F

**Comment by artur-barsegyan** [comment]
Fixed.

**Comment by ligurio** [comment]
![image](https://user-images.githubusercontent.com/1151557/95565849-70f56780-0a29-11eb-98c6-99ef50e16e2a.png)

Lighthouse still shows low performance - 29 (lower than on March 27)

**Comment by ligurio** [comment]
Looks like it was not fixed.

**Comment by patiencedaur** [comment]
Looks like it's closed. Please report similar issues to the DevX team.

**Comment by ligurio** [comment]
> Looks like it's closed.

Please provide any proofs if you think so.

**Comment by ligurio** [comment]
![Screenshot from 2022-02-18 13-26-30](https://user-images.githubusercontent.com/1151557/154665035-499084a4-1e84-4494-8b50-d450a81040df.png)

**Comment by patiencedaur** [comment]
> Please provide any proofs why do you think so.

A lot has been done in this epic: https://github.com/tarantool/tarantool.io-frontend/issues/54
I see that the performance has increased from 29 to 77. Do I understand it correctly that you'd like the result to be 90 or higher?

**Comment by patiencedaur** [comment]
@ filonenko-mikhail, who is responsible for the frontend, says:

Давай этот тикет закроем, _работы выполнены, результат 70%_
Для следующих работ надо заводить новый — проводить исследования — лить патчи

(The cursive is mine.)

If you want further improvements, please create a new ticket. Also, according to our product team, this won't be our priority for another year at least.
